CREATE TABLE IF NOT EXISTS product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sku_code VARCHAR(50) NOT NULL COMMENT 'SKU 编码',
    name VARCHAR(100) NOT NULL COMMENT '商品名称',
    barcode VARCHAR(50) NOT NULL UNIQUE COMMENT '条形码',
    stock INT NOT NULL DEFAULT 0 COMMENT '当前库存',
    daily_usage DOUBLE NOT NULL DEFAULT 0.0 COMMENT '日均消耗量',
    lead_time_days INT NOT NULL DEFAULT 7 COMMENT '交货天数',
    safety_stock INT NOT NULL DEFAULT 10 COMMENT '安全库存',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品表';